version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    image: laravel-development
    container_name: api-development
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    networks:
      - app-network
    depends_on:
      - db  # Garante que o banco de dados esteja disponível antes de iniciar o serviço da API

  nginx:
    image: nginx:alpine
    container_name: nginx-development
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/development/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: db-development
    restart: unless-stopped
    environment:
      POSTGRES_USER: laraveluser  # Nome de usuário do banco de dados
      POSTGRES_PASSWORD: laravelpassword  # Senha do banco de dados
      POSTGRES_DB: laraveldb  # Nome do banco de dados
    volumes:
      - pgdata:/var/lib/postgresql/data  # Volume para persistência dos dados
    networks:
      - app-network
      

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: 